
### Men Products
http://localhost:8000/api/productsMen

### Single Men Products

http://localhost:8000/api/productsMen/:id

### Women Products

http://localhost:8000/api/productsWomen

### Single Women Products

http://localhost:8000/api/productsWomen/:id

### Products
http://localhost:8000/api/products

### Single Products

http://localhost:8000/api/products/:id
